version: "v1.0"
name: Prod deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Block 1 prod
    task:
      jobs:
        - name: job1 prod
          commands:
            - echo foo
            - echo bar
        - name: job2 prod
          commands:
            - echo baz
