version: "v1.0"
name: Staging deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Block 1 stg
    task:
      jobs:
        - name: job1 stg
          commands:
            - echo foo
            - echo bar
        - name: job2 stg
          commands:
            - echo baz
